In [1]:
# bank.csv dataset
#Ensembling Technique 
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')


In [2]:
#To load dataset bank.csv
df=pd.read_csv("bank.csv")
#to display first 5 records
df.head()

age  job  marital  education  default  balance  housing  loan  contact  \
0   59    0        1          1        0     2343        1     0        2   
1   56    0        1          1        0       45        0     0        2   
2   41    9        1          1        0     1270        1     0        2   
3   55    7        1          1        0     2476        1     0        2   
4   54    0        1          2        0      184        0     0        2   

   day  month  duration  campaign  pdays  previous  poutcome  deposit  
0    5      8      1042         1     -1         0         3        1  
1    5      8      1467         1     -1         0         3        1  
2    5      8      1389         1     -1         0         3        1  
3    5      8       579         1     -1         0         3        1  
4    5      8       673         2     -1         0         3        1

In [3]:
'''Bank has launch marketing campaning which is based on telephone call and each row actually
representing an information about each telephone call.
Now we predict either customer will subscribe the deposit or not, basis of this information'''

#first, check null values in given dataset
df.isnull().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
deposit      0
dtype: int64

In [4]:
df.info()#datatype check

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11162 entries, 0 to 11161
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        11162 non-null  int64
 1   job        11162 non-null  int64
 2   marital    11162 non-null  int64
 3   education  11162 non-null  int64
 4   default    11162 non-null  int64
 5   balance    11162 non-null  int64
 6   housing    11162 non-null  int64
 7   loan       11162 non-null  int64
 8   contact    11162 non-null  int64
 9   day        11162 non-null  int64
 10  month      11162 non-null  int64
 11  duration   11162 non-null  int64
 12  campaign   11162 non-null  int64
 13  pdays      11162 non-null  int64
 14  previous   11162 non-null  int64
 15  poutcome   11162 non-null  int64
 16  deposit    11162 non-null  int64
dtypes: int64(17)
memory usage: 1.4 MB


In [5]:
#select Input X and output Y  from given dataset df
X=df.drop("deposit",axis=1) #input features
Y=df["deposit"]#output features

In [6]:
#Train_test_split
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=1)

In [7]:
#User defined function
def create_model(model):
    model.fit(X_train,Y_train)  #train the model
    Y_pred=model.predict(X_test) #Test the model
    print(classification_report(Y_test,Y_pred))
    print("Confusion Matrix ")
    print(confusion_matrix(Y_test,Y_pred))
    return model

In [8]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [9]:
#we take 3 types of classification algorithm to train the dataset
#1. Logistic regression  2. Decision tree(Gini index) 3. DecisionTree(Entropy) 
#call Logistic regression class
from sklearn.linear_model import LogisticRegression
#call decisiontreeclassifier class
from sklearn.tree import DecisionTreeClassifier  #DecisionTreeClassifier inbuilt class

In [10]:
#create object of LogisticRegression
lr=LogisticRegression()
#create object of DecisionTreeClassifier with gini index
dt1=DecisionTreeClassifier() #befault gini index
#create object of DecisionTreeClassifier with entropy
dt2=DecisionTreeClassifier(criterion="entropy")

In [11]:
#Create a model list
model_list=[("Logistic",lr),("DecisionTree-GiniIndex",dt1),("DecisionTree-Entropy",dt2)]
#here model_list is a user defined list object
'''A List consists of multiple tuples and each tuples the first argument has to be a string 
that is a name of the model and second argument has to be a object of model(algorithm)'''

'A List consists of multiple tuples and each tuples the first argument has to be a string \nthat is a name of the model and second argument has to be a object of model(algorithm)'

In [12]:
#Then we need Naive aggregation
#we importing class
from sklearn.ensemble import VotingClassifier  #VotingClassifier inbuilt class

In [13]:
#create object of VotingClassifier  class
vc1=VotingClassifier(estimators=model_list) #here estimators inbuilt parameter of VotingClassifier  
#class , here pass the model_list in this parameter 
#budefault mension hard voting if no define any parameter for hard voting 

In [14]:
#Let call function create_model
vc1=create_model(vc1)

              precision    recall  f1-score   support

           0       0.83      0.82      0.83      1760
           1       0.81      0.81      0.81      1589

    accuracy                           0.82      3349
   macro avg       0.82      0.82      0.82      3349
weighted avg       0.82      0.82      0.82      3349

Confusion Matrix 
[[1451  309]
 [ 302 1287]]


In [15]:
#soft voting 
#create object of VotingClassifier  class
vc2=VotingClassifier(estimators=model_list,voting="soft")#bydefault voting="hard"

In [16]:
#Let call function create_model
vc2=create_model(vc2)

              precision    recall  f1-score   support

           0       0.83      0.82      0.82      1760
           1       0.80      0.81      0.81      1589

    accuracy                           0.82      3349
   macro avg       0.81      0.82      0.82      3349
weighted avg       0.82      0.82      0.82      3349

Confusion Matrix 
[[1444  316]
 [ 302 1287]]


In [17]:
#2. Bootstrapping
#A. Bagging  B. Pasting   C. Random forest

'''Difference between Bagging and pasting classifier : - 
In bagging classifier ,  the model is train with different samples with replacement .
while other hand  in pasting , the model is train with different samples without replacement'''

'Difference between Bagging and pasting classifier : - \nIn bagging classifier ,  the model is train with different samples with replacement .\nwhile other hand  in pasting , the model is train with different samples without replacement'

In [18]:
''' Difference between BNaive aggregation and bootstraping aggregation : -
In naive aggregation , we choose a different types of models(algorithms) or you can say different
types of algorithms and 
In bootstrapping aggregation , We choose only one type of algorithm and each of those algorithm 
a train with different samples '''

' Difference between BNaive aggregation and bootstraping aggregation : -\nIn naive aggregation , we choose a different types of models(algorithms) or you can say different\ntypes of algorithms and \nIn bootstrapping aggregation , We choose only one type of algorithm and each of those algorithm \na train with different samples '

In [19]:
#1. Bagging : call class BaggingClassifier
from sklearn.ensemble import BaggingClassifier

In [20]:
#create object of BaggingClassifier inbuilt class
bc=BaggingClassifier(LogisticRegression(),n_estimators=10,max_samples=10,random_state=1)
#first pass parameter in the function : - we need to pass what type of algorithm be need to use ,suppose 
#we choose to use Logistic regression algo.
#second parameter : - how many algorithm means select n_estimators=10 means we want to 
#10 logistic regression ,
#third parameter : There are 10 logistic regression algo. and each of them will be train on 10
#samples may be 100 (10*10=100)

In [21]:
#call function
bc=create_model(bc)

              precision    recall  f1-score   support

           0       0.76      0.77      0.76      1760
           1       0.74      0.73      0.73      1589

    accuracy                           0.75      3349
   macro avg       0.75      0.75      0.75      3349
weighted avg       0.75      0.75      0.75      3349

Confusion Matrix 
[[1359  401]
 [ 434 1155]]


In [22]:
#Pasting 
#create object of BaggingClassifier inbuilt class
bc1=BaggingClassifier(LogisticRegression(),n_estimators=10,max_samples=10,random_state=1,
                      bootstrap=False) #by default bootstrap parameter=True means use Bagging
#if pass value in parameter bootstrap=False then use pasting

In [23]:
#call function 
bc1=create_model(bc1)

              precision    recall  f1-score   support

           0       0.76      0.77      0.76      1760
           1       0.74      0.73      0.73      1589

    accuracy                           0.75      3349
   macro avg       0.75      0.75      0.75      3349
weighted avg       0.75      0.75      0.75      3349

Confusion Matrix 
[[1359  401]
 [ 434 1155]]


In [24]:
#same score are obtained  in bagging and pasting  
#but better score obtained from voting as compare to bagging and pasting in this dataset bank.csv
#in hard as soft voting : - recall : 81% means .81 which is good score as compare to bagging and 
#pasting

In [25]:
#create object of BaggingClassifier inbuilt class but we choose Algo. DecisionTreeClassifier() means
#gini index means it is called random forest tree
rft=BaggingClassifier(DecisionTreeClassifier(),n_estimators=10,max_samples=600,random_state=1)

In [26]:
#call function
create_model(rft)

              precision    recall  f1-score   support

           0       0.80      0.83      0.82      1760
           1       0.81      0.77      0.79      1589

    accuracy                           0.81      3349
   macro avg       0.81      0.80      0.80      3349
weighted avg       0.81      0.81      0.80      3349

Confusion Matrix 
[[1466  294]
 [ 359 1230]]


BaggingClassifier(base_estimator=DecisionTreeClassifier(ccp_alpha=0.0,
                                                        class_weight=None,
                                                        criterion='gini',
                                                        max_depth=None,
                                                        max_features=None,
                                                        max_leaf_nodes=None,
                                                        min_impurity_decrease=0.0,
                                                        min_impurity_split=None,
                                                        min_samples_leaf=1,
                                                        min_samples_split=2,
                                                        min_weight_fraction_leaf=0.0,
                                                        presort='deprecated',
                                                        random_state=None,


In [27]:
#RandomForestClassifier : inbuilt class for randomforest , call RandomForestClassifier class means
#always use decisiontreeclassifier means select imp features from dataset to predict the output
from sklearn.ensemble import RandomForestClassifier

In [28]:
#create object of RandomForestClassifier class
rf=RandomForestClassifier(n_estimators=10,max_features =10,random_state=1)

In [29]:
#call function
rf=create_model(rf)

              precision    recall  f1-score   support

           0       0.84      0.83      0.84      1760
           1       0.82      0.83      0.82      1589

    accuracy                           0.83      3349
   macro avg       0.83      0.83      0.83      3349
weighted avg       0.83      0.83      0.83      3349

Confusion Matrix 
[[1468  292]
 [ 277 1312]]


In [30]:
#4. Stacking : -  This is Ensembling technique  .
#we install a inbuilt package mlxtend for stacking : - only first time 
#!pip install mlxtend

In [31]:
#call mlxtend package : StackingClassifier inbuilt class
from mlxtend.classifier import StackingClassifier

In [32]:
#create object of LogisticRegression
lr=LogisticRegression()
#create object of DecisionTreeClassifier with gini index
dt1=DecisionTreeClassifier() #befault gini index
#create object of DecisionTreeClassifier with entropy
dt2=DecisionTreeClassifier(criterion="entropy")

In [33]:
#Create the model list 
model_list=[lr,dt1,dt2]
#4th class : it is meta classifier : LogisticRegression  , create object  of meta classifier class
meta=LogisticRegression()  #it is used for meta classifier 

In [34]:
#create the object of StackingClassifier class
sc=StackingClassifier(classifiers=model_list,meta_classifier=meta)

In [35]:

#Now , we train and test the model and generate classification report and confusion matrix 
#then call function
sc=create_model(sc)
#best recall in random forest =0.83 in bank.csv dataset

              precision    recall  f1-score   support

           0       0.83      0.82      0.82      1760
           1       0.80      0.81      0.80      1589

    accuracy                           0.81      3349
   macro avg       0.81      0.81      0.81      3349
weighted avg       0.81      0.81      0.81      3349

Confusion Matrix 
[[1441  319]
 [ 305 1284]]


In [36]:
#3. Boosting Technique : -
#1. ADA Boost : Adaptor boosting 
#call class
from sklearn.ensemble import AdaBoostClassifier

In [37]:
#create the object of AdaBoostClassifier class 
ada=AdaBoostClassifier(n_estimators=100) #passing arguments n_estimators means no. of iteration
#value of this parameter can be <=100 not more than 100 for any dataset
#not mension algorithm name because understood : decision tree ,its create a decision stump

In [38]:
#call function
ada=create_model(ada)

              precision    recall  f1-score   support

           0       0.83      0.86      0.84      1760
           1       0.83      0.80      0.82      1589

    accuracy                           0.83      3349
   macro avg       0.83      0.83      0.83      3349
weighted avg       0.83      0.83      0.83      3349

Confusion Matrix 
[[1505  255]
 [ 317 1272]]


In [39]:
#2. gradient Boost technuique : second tech. of Boosting Ensembling technique 
# GB  : - its create a fully grown tree.this algorithm is focus on short comings 
#short comings means error 

In [40]:
#call inbuilt class GradientBoostingClassifier 
from sklearn.ensemble import GradientBoostingClassifier 

In [41]:
#create the object of GradientBoostingClassifier  class
gbc=GradientBoostingClassifier(n_estimators=100) #here n_estimators can be <=100 
#here n_estimators is inbuilt parameter for iteration 
#GradientBoostingClassifier use always decision tree so not mension alogorithm name

In [42]:
#call function
gbc=create_model(gbc)

              precision    recall  f1-score   support

           0       0.87      0.82      0.84      1760
           1       0.81      0.86      0.83      1589

    accuracy                           0.84      3349
   macro avg       0.84      0.84      0.84      3349
weighted avg       0.84      0.84      0.84      3349

Confusion Matrix 
[[1436  324]
 [ 219 1370]]


In [43]:
#here recall is very good =0.86 as compare other ensembling tech. in ths dataset bank.csv

In [44]:
#3. Extreme Gradient Boosting(XGB) : - this is a gradient boost but this is better version of gradient
#boost. XGB is similar work as GB. 
#Advantages of Extreme Gradient Boosting over Gradient Boosting : -
'''1. It takes less memoryspace means optimising disk space . 
   2. Faster process means processing is very fast
   3. It is very useful to handle huge data
   4. its handle overfitting situation automatic means to overcome the overfitting
   5. Its handle outlier automatic
   6. it use all 
technology means to use multithreading.
   7. in this algo. , inbuilt capability to handle overfitting and outlier
   8. parellel learning'''

'1. It takes less memoryspace means optimising disk space . \n   2. Faster process means processing is very fast\n   3. It is very useful to handle huge data\n   4. its handle overfitting situation automatic means to overcome the overfitting\n   5. Its handle outlier automatic\n   6. it use all \ntechnology means to use multithreading.\n   7. in this algo. , inbuilt capability to handle overfitting and outlier\n   8. parellel learning'

In [45]:
#we instal the package first for XGB : - because it is not define in sklearn package
#then first install package xgboost  only first time

#!pip install xgboost

In [46]:

#call inbuilt class XGBClassifier which define inbuilt package xgboost
from xgboost import XGBClassifier

In [47]:
#create object of XGBClassifier class
xg=XGBClassifier(n_estimators=25,reg_alpha=1) #reg_alpha inbuilt parameter , we pass value 1 means
#to handle automatic overfitting and outlier situation means to overcome the overfitting
#1 means true 

In [48]:
#call function
xg=create_model(xg)

[17:48:34] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
              precision    recall  f1-score   support

           0       0.88      0.82      0.85      1760
           1       0.82      0.88      0.85      1589

    accuracy                           0.85      3349
   macro avg       0.85      0.85      0.85      3349
weighted avg       0.85      0.85      0.85      3349

Confusion Matrix 
[[1449  311]
 [ 197 1392]]
