In [1]:
import numpy as np

In [2]:
#numpy :  single dimensional array means 1 D array use np.array([])
#we create a single dimensional array 
#numpy array means aollection of similar type of data 
#in 1D array , many rows means many records but only one column
A=np.array([67,89,90,56,76,54,98,79,48])

In [3]:
print(A)


[67 89 90 56 76 54 98 79 48]


In [4]:
print(A)

[67 89 90 56 76 54 98 79 48]


In [5]:
print(A)

[67 89 90 56 76 54 98 79 48]


In [6]:
A=np.array([67,89,90,56,76,54,98,79,48])
print(A)

[67 89 90 56 76 54 98 79 48]


In [7]:
A[4]#access value from 4th index

76

In [8]:
#Access value from 3rd index to 6th index one by one then use slicing :
A[3:7] #here start=3rd index and stop=7-1=6th index and step=+1

array([56, 76, 54, 98])

In [9]:
#property of 1D array 
#1. dtype : to show datatype of numpy array A
#2. shaoe : to show How many rows and columns
#3. size :  to show no. of elements in 1D array
#itemsize : to show how much occupy memory by each elements of array
#nbytes : to show total memory occupiesd by Array A in RAM

In [10]:
A.dtype

dtype('int32')

In [11]:
A.shape   #(9,)means 9 records and 1 columns

(9,)

In [12]:
A.size  
#1 byte=8 bits  bits means 0 & 1
#int : each int element occupy  4 bytes memory in ram means 4*8=32 bits

9

In [13]:
A.itemsize

4

In [14]:
A.nbytes  #nbytes means no. of bytes

36

In [15]:
type(A)# To show Which type of VAriable A  ndarray means no. of dimension 

numpy.ndarray

In [16]:
A.ndim

1

In [17]:
A.ndim#to show one dimensional arrey

1

In [18]:
A=np.array([34,67,89.76,43,82])
           

In [19]:
print(A)

[34.   67.   89.76 43.   82.  ]


In [20]:
A=np.array([34,67,89.76,43,82])
print(A)

[34.   67.   89.76 43.   82.  ]


In [21]:
A.size

5

In [22]:
A.nbytes

40

In [23]:
A=np.array([34,67,89.76,43,82],int) 
#forcefully : int (means truncate after decimal)
print(A)

[34 67 89 43 82]


In [24]:
A.dtype

dtype('int32')

In [25]:
#Zeros array : -
X=np.zeros(8) #here 8 means no. of elements=8 in array  by default type float
print(X)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [26]:
#Replace value at 2nd index with 67
X[2]=67
print(X)

[ 0.  0. 67.  0.  0.  0.  0.  0.]


In [27]:
X[0]=87.67
print(X)

[87.67  0.   67.    0.    0.    0.    0.    0.  ]


In [28]:
#Zeros array : -
X=np.zeros(8,int) #create zeros array with 8 elements but force define type int
print(X)

[0 0 0 0 0 0 0 0]


In [29]:
X.dtype

dtype('int32')

In [30]:
X[2]=56.9

In [31]:
print(X)

[ 0  0 56  0  0  0  0  0]


In [32]:
#ones array means fill with value 1
A=np.ones(10) #bydefault type float


In [33]:
print(A)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [34]:
A.nbytes#memory occupied  A arrey in ram

80

In [35]:
A.size

10

In [36]:
A.itemsize

8

In [37]:
#Mathmatical operations in 1D array 

In [38]:
#Mathmatical operations in 1D array 
A=np.array([34,67,89.76,43,82])

In [39]:
print(A)

[34.   67.   89.76 43.   82.  ]


In [40]:
A.sum()#sum of element in 1d arrey

315.76

In [41]:
A.mean()#sum of element/no. of element

63.152

In [42]:
#to find max and min num of 1D arrey

In [43]:
A.max()

89.76

In [44]:
A.min()

34.0

In [45]:
#2D array means Two dimensional Array means many rows means meany records,
#and in each row,many columns  means to store data in tabular form
#numpy : 2D array create then use [[]]
'''
Python   R   ML
 23      32  43
 54      89  65
 67      87  90
 78     38  57
'''

'\nPython   R   ML\n 23      32  43\n 54      89  65\n 67      87  90\n 78     38  57\n'

In [46]:
A=np.array([[23,32,43],[54,89,65],[67,87,90],[78,38,57]])

In [47]:
print(A)

[[23 32 43]
 [54 89 65]
 [67 87 90]
 [78 38 57]]


In [48]:
#to show no. of dimension arrey
A.ndim

2

In [49]:
A.dtype#

dtype('int32')

In [50]:
A.size#to show no of element in A

12

In [51]:
A.itemsize#to show no. of bytes of each element

4

In [52]:
A.nbytes#to show no.of bytes in ram

48

In [53]:
#To show marks of all subjects of 1st index (row)
#A[rowindex,colindex]
print(A[1, ])

[54 89 65]


In [54]:
#To access data at particular row and particular column\
#to access 1st index column of 2nd index row
print(A[2,1])

87


In [55]:
#Access 1st column(1st index) of all students(rows) use slicing
#A[allrows,colstart:colstop] A[start index of row:stop index of row ,colindex ]
print(A[:,1])

[32 89 87 38]


In [56]:
print(A[:,-1])  #access all rows of last column

[43 65 90 57]


In [57]:
print(A[1:4,:3])  #here row index start=1 and stop=4-1=3 and col start=0 
#and stop=3-1=2 means to show 0th col , 1st col and 2nd col of 1st,2nd and 3rd 
#row index

[[54 89 65]
 [67 87 90]
 [78 38 57]]


In [58]:
#sum of all elements of 2D array A
A.sum()

723

In [59]:
#Rowsise sum of elements in array A
A.sum(axis=1)

array([ 98, 208, 244, 173])

In [60]:
#columwise sum of elements in array A
A.sum(axis=0)

array([222, 246, 255])

In [61]:
#Find average of all elements in array means find mean
A.mean()

60.25

In [62]:
#Rowwise mean of elements in array A
print(A.mean(axis=1))

[32.66666667 69.33333333 81.33333333 57.66666667]


In [63]:
#colwise mean of elements in array A
print(A.mean(axis=0))

[55.5  61.5  63.75]


In [64]:
print(A)

[[23 32 43]
 [54 89 65]
 [67 87 90]
 [78 38 57]]


In [65]:
#Find the transpose of Matrix A then use transpose() inbuilt function
#transpose means interchange row and columns
print(A.transpose())

[[23 54 67 78]
 [32 89 87 38]
 [43 65 90 57]]


In [66]:
##use flatten() ==>Its convert two dimensional array to single dimensional array
print(A.flatten())

[23 32 43 54 89 65 67 87 90 78 38 57]


In [67]:
#zeros array in 2D Array
X=np.zeros((4,3)) #here 4 no. of rows and 3 no. of columns bydefault type float
print(X)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [68]:
#zeros array in 2D Array
X=np.zeros((4,3),int) #here 4 no. of rows and 3 no. of columns 
print(X)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [69]:
X[1,2]=88 #repalce the value of 0 with 88 in 1st row index and 2nd colindex
print(X)

[[ 0  0  0]
 [ 0  0 88]
 [ 0  0  0]
 [ 0  0  0]]


In [70]:
#ones array in 2D Array
X=np.ones((4,4)) #here 4 no. of rows and 4 no. of columns bydefault type float
print(X)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [71]:
#create Identity matrix 4*4 then use inbuilt fucntion of numpy ==>eye()
I=np.eye(4,dtype=int) #4 means 4 rows and3 cols  and bydefault datatype =float
print(I)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [72]:
#create Identity matrix 2*2 then use inbuilt fucntion of numpy ==>eye()
I=np.eye(2) #2 means 2 rows and 2 cols  and bydefault datatype =float
print(I)

[[1. 0.]
 [0. 1.]]


In [73]:
#create Identity matrix 3*3 then use inbuilt fucntion of numpy ==>eye()
I=np.eye(3) #3 means 3 rows and3 cols  and bydefault datatype =float
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [74]:
#another method to create a Single Dimensional Array (1 D) : arange() inbuilt
#method
A=np.arange(2,21) #here start=2 and stop=21 means 21-1=20 and step =+1 
#(because not mension)
print(A)

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [75]:
A=np.arange(2,21,2)#step=+2

In [76]:
print(A)

[ 2  4  6  8 10 12 14 16 18 20]


In [77]:
A=np.arange(10,20)

In [78]:
print(A)

[10 11 12 13 14 15 16 17 18 19]


In [79]:
#To change 1D array to 2 D array of A array then use reshape() inbuilt function
#no. of rows=5 and no.of cols=2 means 5*2=10
B=A.reshape(5,2)
print(B)

[[10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [80]:
#Boardcasting in numpy 
#for eg.  2D array A
A=np.array([[1,2,3,4],[10,20,30,40],[100,200,300,400]])


In [81]:
print(A)

[[  1   2   3   4]
 [ 10  20  30  40]
 [100 200 300 400]]


In [82]:
#Create B array
B=np.array([[5,6,7,8]])
print(B)


[[5 6 7 8]]


In [83]:
A+B

array([[  6,   8,  10,  12],
       [ 15,  26,  37,  48],
       [105, 206, 307, 408]])

In [84]:
import numpy as np

In [85]:
#BoardCasting in numpy
#create 2D Array  A 4*3
A=np.array([[10,20,30],[1,2,3],[5,6,7],[20,30,40]])
print(A)

[[10 20 30]
 [ 1  2  3]
 [ 5  6  7]
 [20 30 40]]


In [86]:
#create  2D array B 1*3
B=np.array([[5,7,9]])

In [87]:
print(B)

[[5 7 9]]


In [88]:
A+B

array([[15, 27, 39],
       [ 6,  9, 12],
       [10, 13, 16],
       [25, 37, 49]])

In [89]:
#vactorization means#Vactorization : to apply any mathmatical operations on 2D array 
#means to add/subtract/multply/divide of constant value with array

In [90]:
print(A)

[[10 20 30]
 [ 1  2  3]
 [ 5  6  7]
 [20 30 40]]


In [91]:
B=5

In [92]:
print(A+B)

[[15 25 35]
 [ 6  7  8]
 [10 11 12]
 [25 35 45]]


In [93]:
#concatenate(( )) means to join 2 or more array 
#apply 1 D apply
A=np.array([10,20,30,40])
B=np.array([4,5,6])
C=np.array([7,8,9,10,11])

In [94]:
print(A)

[10 20 30 40]


In [95]:
print(B)

[4 5 6]


In [96]:
print(C)

[ 7  8  9 10 11]


In [97]:
#concate A,B and C array and hold in new array D
D=np.concatenate((A,B,C))
print(D)

[10 20 30 40  4  5  6  7  8  9 10 11]


In [98]:
#suppose Create Matrix A and B both are 2*2
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])


In [99]:
#Concate of matrix A and B (2D array)
np.concatenate((A,B))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [100]:
#concate of matrix A and B
np.concatenate((A,B),axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [5]:
import os

In [7]:
os.getcwd()

'C:\\Users\\ncman'

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("mobile2.csv")
df

a-link-normal href  \
0   https://www.amazon.in/Redmi-9A-2GB-32GB-Storag...   
1   https://www.amazon.in/Redmi-9A-Midnight-3GB-32...   
2   https://www.amazon.in/Panasonic-Storage-Finger...   
3   https://www.amazon.in/Lava-Z66-Marine-Blue-Sto...   
4   https://www.amazon.in/Redmi-8A-Dual-Blue-Stora...   
5   https://www.amazon.in/Nillkin-Realme-Super-Fro...   
6   https://www.amazon.in/KALL-K320-6-53-64GB-Purp...   
7   https://www.amazon.in/Redmi-8A-Dual-White-Stor...   
8   https://www.amazon.in/Redmi-8A-Dual-Midnight-S...   
9   https://www.amazon.in/Vivo-Fusion-Storage-Addi...   
10  https://www.amazon.in/Samsung-Galaxy-Electric-...   
11  https://www.amazon.in/Nokia-C3-Android-Smartph...   
12  https://www.amazon.in/Lenovo-Black-Storage-400...   
13  https://www.amazon.in/Redmi-8A-Dual-Midnight-S...   
14  https://www.amazon.in/Samsung-Galaxy-Storage-A...   
15  https://www.amazon.in/Redmi-6A-Black-2GBRAM-St...   

                                          s-image src  \
0   https://m.media-amazon.com/images/I/710fuhtgIS...   
1   https://m.media-amazon.com/images/I/712Ex7xDnd...   
2   https://m.media-amazon.com/images/I/41QsvcpKaZ...   
3   https://m.media-amazon.com/images/I/61U+VB+kTi...   
4   https://m.media-amazon.com/images/I/71yXShgxvp...   
5   https://m.media-amazon.com/images/I/51j8kd6VPH...   
6   https://m.media-amazon.com/images/I/616xXmVTlJ...   
7   https://m.media-amazon.com/images/I/710p2f-zAd...   
8   https://m.media-amazon.com/images/I/71h+C9wJCj...   
9   https://m.media-amazon.com/images/I/51ZoulFBPG...   
10  https://m.media-amazon.com/images/I/710weRkP-n...   
11  https://m.media-amazon.com/images/I/71Vh6ktdqM...   
12  https://m.media-amazon.com/images/I/317jmcaI6P...   
13  https://m.media-amazon.com/images/I/71h+C9wJCj...   
14  https://m.media-amazon.com/images/I/71ahT-X2Fg...   
15  https://m.media-amazon.com/images/I/718oiyc2ql...   

                                        a-size-medium a-popover-trigger href  \
0      Redmi 9A (Nature Green, 2GB Ram, 32GB Storage)     javascript:void(0)   
1    Redmi 9A (Midnight Black, 3GB Ram, 32GB Storage)     javascript:void(0)   
2   Panasonic Eluga i7 (2GB RAM, 16GB Storage, Fin...     javascript:void(0)   
3       Lava Z66 (Marine Blue, 3GB RAM, 32GB Storage)     javascript:void(0)   
4   Redmi 8A Dual (Sea Blue, 3GB RAM, 32GB Storage...     javascript:void(0)   
5   Nillkin Case for Oppo Realme Real Me 6 / Realm...                    NaN   
6              I KALL K320 (6.53, 4GB, 64GB) (Purple)     javascript:void(0)   
7   Redmi 8A Dual (Sky White, 3GB RAM, 64GB Storag...     javascript:void(0)   
8   Redmi 8A Dual (Midnight Grey, 3GB RAM, 64GB St...     javascript:void(0)   
9   Vivo Y91i (Fusion Black, 2GB RAM, 32GB Storage...     javascript:void(0)   
10  Samsung Galaxy M51 (Electric Blue, 6GB RAM, 12...     javascript:void(0)   
11  Nokia C3 Android 10 Smartphone with 2GB RAM 16...     javascript:void(0)   
12  Lenovo A7 (Black, 4GB RAM, 64GB Storage, 4000m...     javascript:void(0)   
13  Redmi 8A Dual (Midnight Grey, 3GB RAM, 32GB St...     javascript:void(0)   
14  Samsung Galaxy M01 Core (Blue, 1GB RAM, 16GB S...     javascript:void(0)   
15         Mi Redmi 6A (Black, 2GB RAM, 16GB Storage)     javascript:void(0)   

            a-icon-alt                               a-link-normal href 3  \
0   4.1 out of 5 stars  https://www.amazon.in/Redmi-9A-2GB-32GB-Storag...   
1   4.1 out of 5 stars  https://www.amazon.in/Redmi-9A-Midnight-3GB-32...   
2   2.8 out of 5 stars  https://www.amazon.in/Panasonic-Storage-Finger...   
3   4.1 out of 5 stars  https://www.amazon.in/Lava-Z66-Marine-Blue-Sto...   
4   4.0 out of 5 stars  https://www.amazon.in/Redmi-8A-Dual-Blue-Stora...   
5                  NaN                                                NaN   
6   5.0 out of 5 stars  https://www.amazon.in/KALL-K320-6-53-64GB-Purp...   
7   4.0 out of 5 stars  https://www.amazon.in/Redmi-8A-Dual-White-Stor...   
8   4.0 out of 5 stars  https://www.amazo